spring.application.name=eventos

jwt.secret = ${JWT_SECRET}

#86400000 = 24 horas (1 dia)
jwt.expiration = 86400000


#CONFIGURAÇÕES PARA TESTES, IREI EXCLUIR DEPOIS

spring.docker.compose.enabled=false

# =======================================================
# 2. CONFIGURA O BANCO EM MEMÓRIA H2
#    (O Spring vai criar as tabelas automaticamente)
# =======================================================
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Bônus: Habilita o console do H2
# (Acesse em: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
